### fetch all users

GET http://localhost:3000/users

### Create a new user

POST http://localhost:3000/users/new
Content-Type: application/json

{
    "username": "test5",
    "password": "passtest3"
}


### Good Login

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "test4",
    "password": "passtest3"
}

### Bad Login

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "test4",
    "password": "1213"
}